version: "v2.29.7"
services:
  app-timesheet:
    image: azizhendili/tp-foyer:5.0.0
    restart: on-failure
    ports:
      - 8082:8082
    environment:
      SPRING_APPLICATION_JSON: '{
      "spring.datasource.url" : "jdbc:mysql://192.168.50.4:3306/db?createDatabaseIfNotExist=true" ,
      "spring.datasource.username": "springuser",
      "spring.datasource.password": "springpassword",
      "spring.jpa.show-sql": "true",
      "spring.jpa.hibernate.ddl-auto": "update",
      "spring.jpa.properties.hibernate.dialect": "org.hibernate.dialect.MySQLDialect"
    }'
    stdin_open: true
    tty: true
volumes:
  db:
