version: '3.8'

services:
  jenkins:
    container_name: jenkins
    image: selimrachdi5erpbi7-jenkins
    restart: unless-stopped
    ports:
      - "8080:8080"
    volumes:
      - jenkins_home:/var/jenkins_home

  mysql:
    container_name: mysql
    image: mysql:8.0
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: your_password  # Change as needed
    volumes:
      - mysql_data:/var/lib/mysql

  nexus:
    container_name: nexus
    image: sonatype/nexus3
    restart: unless-stopped
    ports:
      - "8081:8081"
    volumes:
      - nexus-data:/nexus-data

  sonarqube:
    container_name: sonarqube
    image: sonarqube
    restart: unless-stopped
    ports:
      - "9000:9000"
    volumes:
      - sonarqube_data:/opt/sonarqube/data

volumes:
  jenkins_home:
  mysql_data:
  nexus_data:
  sonarqube_data:
