version: "v2.29.7"
services:
  mysqldb:
    image: mysql:5.7
    restart: unless-stopped
    environment:
      - MYSQL_ROOT_PASSWORD=
      - MYSQL_DATABASE=db
    ports:
      - 3307:3307
    volumes:
      - db:/var/lib/mysql
  app-timesheet:
    depends_on:
      - mysqldb
    image: azizhendili/tp-foyer:5.0.0
    restart: on-failure
    ports:
      - 8082:8082
    environment:
      SPRING_APPLICATION_JSON: '{
      "spring.profiles.active" : "docker" ,
      "spring.datasource.url" : "jdbc:mysql://mysqldb:3307/db?createDatabaseIfNotExist=true" ,
      "spring.datasource.username" : "root",
      "spring.datasource.password" : null,
      "spring. jpa.properties.hibernate.dialect" : "org.hibernate.dialect.MySQL5InnoDBDialect",
      "spring.jpa.hibernate.ddl-auto" : "update"
    }'
    stdin_open: true
    tty: true
volumes:
  db:
